CRUD for fieldOfActivity
EdiOancea/ferret-api pull request #11
Opened 2019-04-22 08:58 UTC by EdiOancea

2019-05-06 05:44 UTC, lgnstn requested changes

2019-05-06 05:44 UTC, lgnstn commented on app/controllers/crudController.js
> +module.exports = name => {
I think a better idea is to add a `constructor` to the `Controller` class and pass the service name in the constructor. Then you can export the class here and you instantiate it in the actual controller file.

2019-05-06 05:44 UTC, lgnstn commented on app/repositories/address.js
> +  get(id) {
You can do the thing you did for the controllers here, for the repositories as well. You can have a base repository class where you implement the common methods and these specific repositories can extend the base one.

2019-05-06 05:44 UTC, lgnstn commented on app/controllers/address.js
> +module.exports = crudController('address');
I would create a class `AddressController` which extends the base controller, then `module.exports = new AddressController('address');`.

2019-05-06 05:44 UTC, lgnstn commented on app/services/fieldOfActivity.js
> +class FieldOfActivityService {
Same thing for services :)

2019-05-06 12:17 UTC, EdiOancea commented
@lgnstn updated

2019-05-13 07:12 UTC, lgnstn approved these changes

2019-05-13 07:12 UTC, merged