Company crud
EdiOancea/ferret-api pull request #12
Opened 2019-05-07 13:19 UTC by EdiOancea

2019-05-07 13:20 UTC, EdiOancea commented
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD for company](https://trello.com/c/OY8nykdi/9-crud-for-company)

2019-05-13 07:13 UTC, lgnstn commented
@EdiOancea Please resolve conflicts.

2019-05-13 13:54 UTC, EdiOancea commented
@lgnstn updated

2019-05-16 05:32 UTC, lgnstn requested changes

2019-05-16 05:32 UTC, lgnstn commented on app/services/user.js
> +    if (user.companyId) {
Why do you have this here? When a user is created it has nothing to do with a company.

2019-05-16 05:32 UTC, lgnstn commented on app/services/user.js
> +    if (newData.companyId) {
Same here.

2019-05-16 05:32 UTC, lgnstn commented on fixtures/address.js
> +  ...companyFixture,
Why?

2019-05-16 05:32 UTC, lgnstn commented on fixtures/company.js
> +  ...fieldOfActivityFixture,
Why?

2019-05-16 05:32 UTC, lgnstn commented on fixtures/user.js
> +  ...companyFixture,
Why?

2019-05-22 07:34 UTC, lgnstn approved these changes

2019-05-22 07:34 UTC, merged