Add a timetable field to company.
EdiOancea/ferret-api pull request #14
Opened 2019-05-29 12:11 UTC by laurandarius

Closes #13

2019-05-29 12:16 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a timetable field to company](https://trello.com/c/oMEwLOCi/12-add-a-timetable-field-to-company)

2019-05-31 05:22 UTC, lgnstn requested changes

2019-05-31 05:22 UTC, lgnstn commented on app/services/company.js
> +    if (company.timetable === undefined) {
This is not necessary. The field will be validated by Sequelize based on the rules you set.

2019-05-31 08:12 UTC, laurandarius commented
@lgnstn updated.

2019-06-04 11:46 UTC, lgnstn approved these changes

2019-06-04 11:46 UTC, merged