Add possibility to upload images to company.
EdiOancea/ferret-api pull request #15
Opened 2019-06-07 09:38 UTC by laurandarius

2019-06-07 09:38 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the possiblity to upload images to a company.](https://trello.com/c/BIGiwdKQ/13-add-the-possiblity-to-upload-images-to-a-company)

2019-06-10 06:19 UTC, lgnstn requested changes

2019-06-10 06:19 UTC, lgnstn commented on app/migrations/20190604123759-create-file.js
> +          model: 'companies',
This field doesn't references only the company. Together with entity type it can reference any entity.

2019-06-10 06:19 UTC, lgnstn commented on app/models/company.js
> +    Company.hasMany(models.files, {
Please remove this.

2019-06-10 06:19 UTC, lgnstn commented on app/models/file.js
> +  File.associate = models => {
Please remove this.

2019-06-10 06:19 UTC, lgnstn commented on app/seeders/20190606083218-demo-field-of-activity.js
> +    name: 'Test Name',
You can use something that looks like a field of activity. It will be more helpful when testing.

2019-06-10 06:19 UTC, lgnstn commented on index.js
> +    const destFolder = req.path.split('/')[2];
The path you use to upload a file can change and this code won't work anymore.
Here I would only save the file in a temporary folder, `tmp`. Then, in the service responsible for the company I would call a file service that will move the file in the correct folder.

2019-06-10 06:19 UTC, lgnstn commented on app/models/file.js
> +  }, {
Please save the original file name as well.

2019-06-10 06:19 UTC, lgnstn commented on index.js
> +      cb(null, `${raw.toString('hex')}-${Date.now()}${path.extname(file.originalname)}`);
I recommend you to use https://www.npmjs.com/package/uuid. It is the best way to generate unique values.

2019-06-10 12:12 UTC, laurandarius commented
@lgnstn updated.

2019-06-24 07:10 UTC, lgnstn requested changes

2019-06-24 07:10 UTC, lgnstn commented on app/models/file.js
> +    filename: {
Please rename this field `originalFileName`.

2019-06-24 07:10 UTC, lgnstn commented on app/services/file.js
> +    const fileExists = await fileRepository.getByPropsNonParanoid(newFile);
I doesn't make sense to make this check here. Please remove it.

2019-06-24 07:10 UTC, lgnstn commented on app/services/file.js
> +    if (newData.id !== undefined) {
Here you should verify that only the original file name is changed.

2019-06-24 07:10 UTC, lgnstn commented on app/services/file.js
> +};
The delete function is missing, where you should remove the file saved on disk.

2019-06-24 07:10 UTC, lgnstn commented on index.js
> +global.__basedir = __dirname;
Please avoid using global variables. A better approach is to use a config file where you define the tmp folder and the one used as final destination. Then you can import that config everywhere.

2019-06-25 07:28 UTC, laurandarius commented
@lgnstn updated.

2019-07-16 06:31 UTC, lgnstn approved these changes

2019-07-16 06:32 UTC, merged