Add Appointment table and CRUD.
EdiOancea/ferret-api pull request #18
Opened 2019-06-27 09:15 UTC by laurandarius

2019-06-27 09:15 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Appointment entity + CRUD.](https://trello.com/c/AVLsXnH7/16-add-appointment-entity-crud)

2019-07-16 06:42 UTC, lgnstn requested changes

2019-07-16 06:42 UTC, lgnstn commented on app/services/appointment.js
> +      const fieldExists = await companyService.get(companyId);
This variable is not used. Please remove it.

2019-07-16 06:42 UTC, lgnstn commented on app/services/appointment.js
> +    const appointmentExists = await this.repository.getByPropsNonParanoid({ ...appointment });
I think here you should also validate that this appointment doesn't overlap with another one.

2019-07-19 12:27 UTC, laurandarius commented
@lgnstn updated.

2019-07-23 08:26 UTC, lgnstn approved these changes

2019-07-23 08:27 UTC, lgnstn commented
@laurandarius Conflicts.

2019-07-23 12:13 UTC, laurandarius commented
@lgnstn updated.

2019-07-24 06:23 UTC, merged