Fix service expected fieldOfActivityId behaviour.
EdiOancea/ferret-api pull request #19
Opened 2019-06-28 08:23 UTC by laurandarius

2019-06-28 08:24 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Company service expects "fieldOfActivityId" property but "business" is provided.](https://trello.com/c/u1N7ZfWA/17-company-service-expects-fieldofactivityid-property-but-business-is-provided)

2019-07-16 06:44 UTC, lgnstn requested changes

2019-07-16 06:44 UTC, lgnstn commented on app/services/company.js
> +      const fieldExists = await fieldOfActivityRepository.getByPropsNonParanoid({ name: business });
This is not the best name for this variable. Here I consider it a boolean value, but a few lines below I see that it is in fac an object. I would call it "fieldOfActivity".

2019-07-16 06:44 UTC, lgnstn commented on app/services/company.js
> +      const fieldExists = await fieldOfActivityRepository.getByPropsNonParanoid({ name: business });
Same here.

2019-07-17 13:18 UTC, laurandarius commented
@lgnstn updated.

2019-07-23 08:27 UTC, lgnstn approved these changes

2019-07-23 08:28 UTC, lgnstn commented
@laurandarius Conflict.

2019-07-23 12:14 UTC, laurandarius commented
@lgnstn updated.

2019-07-24 06:24 UTC, merged