Add endpoint GET /api/companies/ for the ListCompanies feature.
EdiOancea/ferret-api pull request #21
Opened 2019-07-17 13:38 UTC by laurandarius

2019-07-17 13:38 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add endpoint GET /api/companies/ for the ListCompanies feature.](https://trello.com/c/NMp7R7Zt/19-add-endpoint-get-api-companies-for-the-listcompanies-feature)

2019-07-23 08:30 UTC, lgnstn requested changes

2019-07-23 08:30 UTC, lgnstn commented on app/repositories/company.js
> +    return db.companies.findAll({ raw: true});
Missing space before `}`.

2019-07-23 08:30 UTC, lgnstn commented on app/services/company.js
> +    const found = await companyRepository.getAll();
You can directly return this.

2019-07-23 08:33 UTC, lgnstn requested changes

2019-07-23 08:33 UTC, lgnstn commented on app/repositories/company.js
> +    return db.companies.findAll({ raw: true});
I think it is best to add this method here https://github.com/EdiOancea/ferret-api/blob/master/app/services/crudService.js

2019-07-24 11:43 UTC, laurandarius commented
@lgnstn updated.

2019-07-25 06:25 UTC, lgnstn requested changes

2019-07-25 06:25 UTC, lgnstn commented on app/routes/company.js
> +const express = require('express');
Why?

2019-07-25 06:25 UTC, lgnstn commented on tmp/.gitignore
> +# Ignore everything in this directory
Can't you use the global git ignore file?

2019-07-25 12:05 UTC, laurandarius commented
@lgnstn updated.

2019-07-26 07:47 UTC, lgnstn requested changes

2019-07-26 07:47 UTC, lgnstn commented on app/controllers/company.js
> +  async getAll(req, res, next) {
Please add the `getAll` method in `CrudController`.

2019-07-26 09:00 UTC, laurandarius commented
@lgnstn updated again.

2019-07-30 06:01 UTC, lgnstn approved these changes

2019-07-30 06:01 UTC, merged