Return address and images on GET /companies/:id endpoint.
EdiOancea/ferret-api pull request #22
Opened 2019-07-18 09:31 UTC by laurandarius

2019-07-18 09:31 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Return address and images on GET /companies/:id endpoint.](https://trello.com/c/GUg2CPBA/20-return-address-and-images-on-get-companies-id-endpoint)

2019-07-23 09:14 UTC, lgnstn requested changes

2019-07-23 09:14 UTC, lgnstn commented on app/services/company.js
> +    let found = await companyRepository.get(id);
This should be named `company`.

2019-07-23 09:14 UTC, lgnstn commented on app/services/company.js
> +    const fieldOfActivity =
Please indent it this way:
```
const fieldOfActivity = await fieldOfActivityRepository
    .get(fieldOfActivityId);
```

2019-07-23 09:14 UTC, lgnstn commented on app/services/company.js
> +    if (business !== undefined) {
This validation logic is taking too much space in this service. Please create another class that handles the validation.

2019-07-23 09:14 UTC, lgnstn commented on app/services/company.js
> +      await addressRepository.create({
Please create a service for the Address if there isn't one already and call it here.

2019-07-23 09:14 UTC, lgnstn commented on config.js
> +module.exports = { tmpFolder, companyFilesFolder, ORIGIN };
Please use CAPITAL letters for all the constant exported here.

2019-07-24 13:48 UTC, laurandarius commented
@lgnstn updated.

2019-07-25 07:30 UTC, lgnstn requested changes

2019-07-25 07:30 UTC, lgnstn commented on app/services/company.js
> +    if (!fieldOfActivity) {
You can move this check in the validator as well.

2019-07-25 07:30 UTC, lgnstn commented on app/services/company.js
> +    if (address !== undefined) {
This whole block should be inside the address service.

2019-07-25 07:30 UTC, lgnstn commented on app/services/company.js
> +    const companyExists = await this.repository.get(id);
1) `companyExists` makes me think this is a boolean value, but in fact it is a company. Please rename it.
2) this check should be in the validator.

2019-07-25 07:30 UTC, lgnstn commented on app/services/company.js
> +    const companyExists = await this.repository.get(id);
Same.

2019-07-25 13:36 UTC, laurandarius commented
@lgnstn updated.

2019-07-26 07:53 UTC, lgnstn requested changes

2019-07-26 07:53 UTC, lgnstn commented on app/services/address.js
> +    const existingAddress = await addressRepository.getByPropsNonParanoid(address);
Please create a validator for the addresses too.

2019-07-26 07:53 UTC, lgnstn commented on app/services/company.js
> +      companyToReturn.address = `${streetName} ${streetNumber}, ap. ${apartmentNumber}, ${city}, ${country}`;
It is better to return the address object (model) and let the front end decide how it wants to display the address.

2019-07-26 07:53 UTC, lgnstn commented on app/validators/company.js
> +    const {
The same code can be found in the method above. This is not ok, the code is not DRY (Don't Repeat Yourself). Please move it in a method and call it in both places.

2019-07-29 10:24 UTC, laurandarius commented
@lgnstn updated.

2019-07-30 06:11 UTC, lgnstn requested changes

2019-07-30 06:11 UTC, lgnstn commented on app/services/address.js
>      return await this.get(createdAddress.id);
You not return here `createdAddress`?

2019-07-30 06:11 UTC, lgnstn commented on app/services/address.js
> +  validatorName: 'address',
Why do you need this? It doesn't look like you use it.

2019-07-30 06:11 UTC, lgnstn commented on app/services/company.js
> +      name: business,
You should have sent the field of activity id from the frontend. Keep this in mind in the future, don't change anything here now.

2019-07-30 09:01 UTC, laurandarius commented
@lgnstn updated.

2019-08-01 05:19 UTC, lgnstn approved these changes

2019-08-01 05:19 UTC, merged