Create validators for each model.
EdiOancea/ferret-api pull request #24
Opened 2019-08-01 12:54 UTC by laurandarius

2019-08-01 12:54 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create validators for each model.](https://trello.com/c/vtjttmDG/22-create-validators-for-each-model)

2019-08-02 07:18 UTC, lgnstn requested changes

2019-08-02 07:18 UTC, lgnstn commented on app/services/companyReview.js
> +    await companyReviewValidator.validateCreate(companyReview, user, companyId);
Why didn't you use the same way of using the validator? With `this.validator.validate...`?

2019-08-02 07:18 UTC, lgnstn commented on app/validators/crudValidator.js
> +    if (record.id !== undefined) {
Do you use this code?

2019-08-02 09:56 UTC, laurandarius commented
@lgnstn updated.

2019-08-06 06:11 UTC, lgnstn approved these changes

2019-08-06 06:11 UTC, merged