Users table
EdiOancea/ferret-api pull request #3
Opened 2019-03-18 14:54 UTC by EdiOancea

2019-03-18 14:58 UTC, EdiOancea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create users table and model](https://trello.com/c/OuZdrkbP/2-create-users-table-and-model)

2019-03-19 06:13 UTC, lgnstn requested changes

2019-03-19 06:13 UTC, lgnstn commented on app.js
> +const Sequelize = require('sequelize');
If you keep adding everything to this file, you will end up with a few thousand lines of code here. I don't think you want this to happen :)
Let's rename this file `index.js` and keep here only the initial content, from the previous PR.
Then create a folder `app` and `app/models`. In `modes` you will add all the models, a separate file for each one, in this case `app/models/user.js`.

2019-03-19 06:13 UTC, lgnstn commented on app.js
> +const connection = new Sequelize({
Please move this connection into `app/models/index.js`. And then I'll show you how you can load all the models automatically.

2019-03-19 06:13 UTC, lgnstn commented on app.js
> +const User = connection.define('user', {
As I said, this goes into `app/models/user.js`.

2019-03-19 06:13 UTC, lgnstn commented on app.js
> +const User = connection.define('user', {
I know I didn't say anything about this, but we are going to use DB migrations to handle database changes :)

2019-03-19 06:13 UTC, lgnstn commented on app.js
> +    field: 'email',
You sure?

2019-03-19 16:21 UTC, EdiOancea commented
@lgnstn updated

2019-03-20 08:04 UTC, lgnstn requested changes

2019-03-20 08:04 UTC, lgnstn commented on app/models/user.js
> +        firstNameValidator: (value) => {
There should be something like pattern validator. This is too much/complicated.

2019-03-20 08:04 UTC, lgnstn commented on app/models/user.js
> +  User.associate = function(models) {
Please remove it if it does nothing.

2019-03-20 08:04 UTC, lgnstn commented on app/migrations/20190319143718-create-user.js
> +        min: 0,
Please remove these.

2019-03-20 08:39 UTC, EdiOancea commented
@lgnstn updated

2019-03-20 11:44 UTC, lgnstn commented
@EdiOancea Please resolve the conflicts. Thanks!

2019-03-21 06:29 UTC, lgnstn approved these changes

2019-03-21 06:29 UTC, merged