Login endpoint
EdiOancea/ferret-api pull request #7
Opened 2019-04-08 14:27 UTC by EdiOancea

2019-04-08 14:35 UTC, EdiOancea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login endpoint](https://trello.com/c/dXEfNHvW/4-login-endpoint)

2019-04-09 07:02 UTC, lgnstn commented
@EdiOancea Please resolve conflicts.

2019-04-09 09:00 UTC, EdiOancea commented
@lgnstn updated

2019-04-10 07:11 UTC, lgnstn requested changes

2019-04-10 07:11 UTC, lgnstn commented on app/services/signin.js
> +      errorService.throwValidationError("Invalid email.");
You don't want to give details about why the authentication didn't succeeded (security reasons). All the errors should say "Wrong credentials" or something like this.

2019-04-10 07:11 UTC, lgnstn commented on app/services/signin.js
> +    return await jwt.sign({ id: user.id }, privateKey, { expiresIn: 3600 });
I think this is a sync operation, you don't need `await`.

2019-04-10 07:11 UTC, lgnstn commented on app/controllers/signin.js
> +    res.json(await signinService.authenticate(req.body));
Please use an envelope like this `{ token: await signinService.authenticate(req.body) }`.
 
Also good to know: https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/

2019-04-10 07:11 UTC, lgnstn commented on test/signin.test.js
> +const privateKey = process.env.API_KEY;
Please rename it `JWT_SECRET` and add a `.env.sample` file with dummy data for all the env variables (basically a copy of `.env` with dummy data for sensitive info).

2019-04-10 08:08 UTC, EdiOancea commented
@lgnstn updated

2019-04-11 06:47 UTC, lgnstn approved these changes

2019-04-11 06:47 UTC, merged